version: 2.1 # This must be the very first line, with no leading spaces

# Define reusable executors (execution environments)
# This promotes consistency and reusability across jobs.
executors:
  # Executor for Node.js based jobs
  node-executor:
    docker:
      - image: cimg/node:18.17.0
    resource_class: small

# Define reusable commands (sequences of steps)
commands:
  restore_npm_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
  save_npm_cache:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.lock.json" }}

jobs:
  build_and_test:
    executor: node-executor
    steps:
      - checkout
      - restore_npm_cache
      - run:
          name: Install Dependencies
          command: npm ci
      - save_npm_cache
      - run:
          name: Run Linting
          command: npm run lint
      - run:
          name: Run Tests with Coverage
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_docker_image:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            IMAGE_NAME="mrlamar237/cicd-pipeline-demo"
            # Explicitly specify the Dockerfile path.
            # This ensures that even if context changes, it finds the Dockerfile.
            docker build -f Dockerfile -t ${IMAGE_NAME}:${CIRCLE_SHA1} -t ${IMAGE_NAME}:latest .
      - run:
          name: Verify Docker Images # NEW DIAGNOSTIC STEP
          command: docker images # List all the local Docker images to check for the newly built one
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            IMAGE_NAME="mrlamar237/cicd-pipeline-demo"
            docker push ${IMAGE_NAME}:${CIRCLE_SHA1}
            docker push ${IMAGE_NAME}:latest

  deploy_to_cloud:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy Application to Cloud (Placeholder)
          command: |
            echo "Starting deployment to cloud platform..."
            REMOTE_HOST="your-cloud-server-ip-or-dns"
            REMOTE_USER="your-ssh-user"

            ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "
              echo '$DOCKER_HUB_PASSWORD' | docker login -u '$DOCKER_HUB_USERNAME' --password-stdin
            "

            ssh -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "
              docker pull mrlamar237/cicd-pipeline-demo:latest
              docker stop cicd-demo-app || true
              docker rm cicd-demo-app || true
              docker run -d -p 80:3000 --name cicd-demo-app \
              -e PORT=3000 \
              -e NODE_ENV=production \
              -e APP_VERSION=${CIRCLE_SHA1} \
              -e GIT_COMMIT=${CIRCLE_SHA1} \
              mrlamar237/cicd-pipeline-demo:latest
            "
            echo "Deployment initiated. Verify application at http://${REMOTE_HOST}/health"

workflows:
  build_test_and_deploy_workflow:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - deploy_to_cloud:
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - master
